// The gambit book (web/book/gambits.json, generated by tools/make_fixture.py from opening_trainer/book.py).
// tests/test_book.py checks the rule; here: the browser reads the same file and finds the same positions.
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { Chess } from '../web/vendor/chess.js@1.4.0/dist/esm/chess.js';
import { BOOK_ID, NO_SKIP, loadGambitBook, parseBook, skips } from '../web/core/book.js';
import { fenKey } from '../web/core/fen.js';

const FILE = new URL('../web/book/gambits.json', import.meta.url);
const book = parseBook(JSON.parse(readFileSync(FILE, 'utf8')));

function fenAfter(moves) {
  const board = new Chess();
  for (const san of moves.split(' ').filter(Boolean)) board.move(san);
  return board.fen();
}
const keyAfter = (moves) => fenKey(fenAfter(moves));

describe('gambit book', () => {
  it('has named gambits and sacrifices that are not called gambits', () => {
    for (const m of ['d4 e5', 'e4 e5 f4', 'e4 e5 Nf3 Nf6 Nxe5 Nc6', 'e4 e5 Nf3 Nc6 Bc4 Bc5 b4',
      'e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7', 'e4 e5 Nf3 Nc6 Nc3 Nf6 Nxe5', 'e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 Bc5',
      'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 O-O c3 d5']) {
      expect(book.has(keyAfter(m)), m).toBe(true);
    }
  });

  it('leaves ordinary and bad moves out', () => {
    for (const m of ['e4 e5 Nf3 f6', 'e4 e5 Qh5', 'e4', 'e4 e5', 'd4 d5']) expect(book.has(keyAfter(m)), m).toBe(false);
  });

  it('refuses another book version', () => {
    expect(() => parseBook({ book: 'old', keys: [] })).toThrow(/expected/);
    expect(parseBook({ book: BOOK_ID, keys: ['k'] })).toEqual(new Set(['k']));
  });

  it('loads through fetch once and retries after a failure', async () => {
    let calls = 0;
    const failing = async () => { calls += 1; return { ok: false, status: 404 }; };
    await expect(loadGambitBook(failing)).rejects.toThrow(/HTTP 404/);
    const ok = async (url) => { calls += 1; return { ok: true, json: async () => JSON.parse(readFileSync(url, 'utf8')) }; };
    const loaded = await loadGambitBook(ok);
    expect(loaded.size).toBe(book.size);
    const before = calls;
    expect(await loadGambitBook(ok)).toBe(loaded);
    expect(calls).toBe(before);
  });
});

describe('skips', () => {
  const after = fenAfter('d4 e5');
  const skip = { book: new Set([keyAfter('d4 e5')]), bookMoves: 1 };

  it('book moves within bookMoves only', () => {
    expect(skips(skip, 1, after)).toBe(true);
    expect(skips(skip, 2, after)).toBe(false);
    expect(skips({ ...skip, bookMoves: 0 }, 1, after)).toBe(false);
    expect(skips(NO_SKIP, 1, after)).toBe(false);
    expect(skips(skip, 1, fenAfter('d4 d5'))).toBe(false);
  });
});
